### ISSUE TITLE
Error when compiling with dcaqe feature

### ISSUE THREAD

**Issue by mh415-f** [ltentrup/caqe#13]
Hi,
first off, thank you for open-sourcing this great solver!
I wanted to compile dCAQE with `cargo build --features dcaqe --release` but I get an error like this
```
error[E0433]: failed to resolve: could not find `DCaqeConfig` in `caqe`
 --> src/bin/dcaqe.rs:6:24
  |
6 |     let config = caqe::DCaqeConfig::new(&args);
  |                        ^^^^^^^^^^^ could not find `DCaqeConfig` in `caqe`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `caqe` due to previous error
warning: build failed, waiting for other jobs to finish...
```
The build without the dcaqe feature works.
Can you provide a fix for this?

Thanks and best regards

**Comment by ltentrup** [comment]
Thank you for your interest in CAQE. The `dcaqe` feature is unsupported and will be removed in the future.
