### ISSUE TITLE
LARGEMEM

### ISSUE THREAD

**Issue by algebravic** [ltentrup/caqe#17]
I built caqe and was running it, but it terminated with the message `ERROR: memory manager can't handle the load`.  How do I recompile with `DLARGEMEM=ON`?  I tried `cargo build -DLARGMEM=ON --release` but that was rejected.

**Comment by ltentrup** [comment]
The error is from the cryptominisat library. To enable this flag use `cargo build --release --features largemem`

**Comment by algebravic** [comment]
Thanks! That worked.
