### ISSUE TITLE
how to build dcaqe?

### ISSUE THREAD

**Issue by hharryyf** [ltentrup/caqe#20]
I tried to build dcaqe by running "cargo build --release" from the root directory, but it seems like the only executable binary I can get in ./target/release/ is caqe, there's no dcaqe binary. Could you please tell me how to build dcaqe?

Thanks.

**Comment by hharryyf** [comment]
When I run `cargo build --release --features dcaqe`
I got this compile error.
![image](https://github.com/user-attachments/assets/b6f573b8-179d-45ac-9ad1-dd6eb6933f12)

**Comment by irfansha** [comment]
I think dcaqe is not available in the current version.
You need to use some previous version, then you can compile it.
I think it is version 2 or something.
