### ISSUE TITLE
Linker error on OpenBSD; can be fixed by treating OpenBSD like MacOS

### ISSUE THREAD

**Issue by falsifian** [ltentrup/caqe#9]
Hi,

When I build with `cargo build --release` (I'm at git commit 356e3dab3) I get linker errors like the following:

`ld: error: undefined symbol: std::__1::cerr`

I was able to fix it locally by making the following change in your `cryptominisat-rs` fork (and updating the `cryptominisat` dep in `Cargo.tml` accordingly):

    diff --git a/build.rs b/build.rs
    index 1310757..f3c93d8 100755
    --- a/build.rs
    +++ b/build.rs
    @@ -30,9 +30,5 @@ fn main() {
         println!("cargo:rustc-link-search=native={}/lib", dst.display());
         println!("cargo:rustc-link-lib=static=cryptominisat5");
     
    -    #[cfg(target_os = "macos")]
         println!("cargo:rustc-flags=-l dylib=c++");
    -
    -    #[cfg(not(target_os = "macos"))]
    -    println!("cargo:rustc-flags=-l dylib=stdc++");
     }

Of course that can't be checked in. Sorry, I know almost no rust and I have no idea what the `#[` syntax is. If you give me a patch I'm happy to test it, or if you give me a couple of pointers (e.g. the syntax for "target os is X or Y" I'm happy to try to craft a better fix.

**Comment by ltentrup** [comment]
Your compilation error should be fixed now. Unfortunately, this does not fix the overall problem. We have to link against the same C++ stdlib that cmsat is linked against, but cmake does not provide this information. Thus, this is merely a heuristic that works in standard environments.

**Comment by falsifian** [comment]
Thanks. d739702 fixes the issue for me. Sorry to hear about the configuration mess.
